### PR TITLE
Better Ship Hud Positioning

### PR DESCRIPTION
**Pull request by JoelOliMclean**
Move Ship Control HUD to centre bottom of the screen for better experience in fpv

### CODE REVIEW

**Comment by devedse** [comment]
Hey @JoelOliMclean,

Would you maybe be able to add a screenshot 😄 . This mainly to document what was done in this PR.

**Comment by JoelOliMclean** [comment]
Sure @devedse , here you go
[https://i.imgur.com/S2mFwt4.jpg](url)

**Comment by devedse** [comment]
image

Thanks, @Nicov3l what do you think of this PR?

**Comment by Nicov3l** [comment]
Thanks! Will be included in the next release (tomorrow?)

**Comment by JoelOliMclean** [comment]
Nice one, cheers guys 😄

**Pull request merged**
